"""Semantic answer cache backed by the ChromaDB 'answers' collection.

Query embeddings are stored alongside the serialised answer JSON.  On lookup,
the cosine similarity between the incoming query embedding and stored query
embeddings is computed; if the closest match exceeds the configured threshold
(default 0.93) the cached answer is returned without re-running the pipeline.

Usage:
    from app.tools.answer_cache import answer_cache

    # Check cache before running the pipeline
    hit = await answer_cache.lookup(query_embedding)
    if hit:
        return hit  # dict with the stored answer

    # After the pipeline produces an answer, store it
    await answer_cache.store(query_text, query_embedding, answer_dict)
"""

from __future__ import annotations

import json
import logging
import uuid
from datetime import datetime, timedelta, timezone

import numpy as np

from app.config import settings

logger = logging.getLogger(__name__)

# Maximum number of cache entries to keep in the collection before pruning.
# This is a soft limit — pruning is done opportunistically on store().
_MAX_CACHE_SIZE = 1000


def _cosine_similarity(a: list[float], b: list[float]) -> float:
    """Compute cosine similarity between two embedding vectors."""
    va = np.array(a, dtype=np.float32)
    vb = np.array(b, dtype=np.float32)
    norm_a = np.linalg.norm(va)
    norm_b = np.linalg.norm(vb)
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return float(np.dot(va, vb) / (norm_a * norm_b))


class AnswerCache:
    """Semantic cache using ChromaDB 'answers' collection.

    Each stored entry has:
        document  — the original query text
        metadata  — {"answer_json": <serialised answer>, "stored_at": <iso>}
        id        — UUID string

    The embedding stored by ChromaDB is the query embedding (generated by the
    same sentence-transformer model used for chunk retrieval).
    """

    def __init__(
        self,
        threshold: float | None = None,
    ) -> None:
        self._threshold = threshold  # None means use settings value at runtime

    def _get_threshold(self) -> float:
        if self._threshold is not None:
            return self._threshold
        return settings.answer_cache_similarity_threshold

    def _collection(self):
        from app.tools.vector_store import get_answers_collection  # noqa: PLC0415

        return get_answers_collection()

    async def lookup(
        self,
        query_embedding: list[float],
        threshold: float | None = None,
    ) -> dict | None:
        """Check whether a semantically similar query has been answered before.

        Args:
            query_embedding: The embedding vector for the incoming query.
            threshold:       Cosine similarity threshold (overrides config).

        Returns:
            The cached answer dict if a sufficiently similar query was found,
            otherwise None.
        """
        effective_threshold = threshold if threshold is not None else self._get_threshold()
        collection = self._collection()

        if collection.count() == 0:
            return None

        try:
            results = collection.query(
                query_embeddings=[query_embedding],
                n_results=1,
                include=["documents", "metadatas", "distances", "embeddings"],
            )
        except Exception as exc:
            logger.error("AnswerCache.lookup: query error — %s", exc)
            return None

        if not results["ids"] or not results["ids"][0]:
            return None

        # ChromaDB returns cosine *distance* in [0, 2] when the collection
        # uses hnsw:space=cosine.  Convert to similarity: sim = 1 - dist/2.
        # We also double-check via explicit dot product for safety.
        stored_embeddings = (results.get("embeddings") or [[]])[0]
        distances = results["distances"][0]

        try:
            has_embeddings = (
                stored_embeddings is not None
                and len(stored_embeddings) > 0
                and stored_embeddings[0] is not None
            )
        except (TypeError, ValueError):
            has_embeddings = False

        if has_embeddings:
            stored_vec = stored_embeddings[0]
            similarity = _cosine_similarity(query_embedding, stored_vec)
        else:
            # Fallback: derive from ChromaDB cosine distance
            dist = distances[0] if distances else 2.0
            similarity = max(0.0, 1.0 - dist / 2.0)

        if similarity < effective_threshold:
            logger.debug(
                "AnswerCache.lookup: closest similarity %.4f < threshold %.4f — miss",
                similarity,
                effective_threshold,
            )
            return None

        metadatas = results["metadatas"][0]
        if not metadatas:
            return None

        # TTL check — treat entries older than 30 days as a miss
        stored_at_str = metadatas[0].get("stored_at", "")
        if stored_at_str:
            try:
                stored_at = datetime.fromisoformat(stored_at_str)
                if datetime.now(timezone.utc) - stored_at > timedelta(days=30):
                    logger.info(
                        "AnswerCache.lookup: entry expired (stored_at=%s) — miss",
                        stored_at_str,
                    )
                    return None
            except (ValueError, TypeError):
                pass  # malformed date — proceed

        raw_json = metadatas[0].get("answer_json", "")
        if not raw_json:
            return None

        try:
            answer = json.loads(raw_json)
            logger.info(
                "AnswerCache.lookup: HIT (similarity=%.4f)",
                similarity,
            )
            return answer
        except json.JSONDecodeError as exc:
            logger.error("AnswerCache.lookup: failed to parse cached JSON — %s", exc)
            return None

    async def store(
        self,
        query_text: str,
        query_embedding: list[float],
        answer: dict,
        paper_ids: list[str] | None = None,
    ) -> None:
        """Store a query embedding and its answer in the cache.

        Args:
            query_text:      The original (normalised) query string.
            query_embedding: The embedding vector for query_text.
            answer:          The answer dict to cache (must be JSON-serialisable).
            paper_ids:       List of paper IDs cited by this answer.  Stored as
                             a comma-separated string so the cache entry can be
                             invalidated when any of those papers is deleted.
        """
        collection = self._collection()

        try:
            answer_json = json.dumps(answer, default=str)
        except (TypeError, ValueError) as exc:
            logger.error("AnswerCache.store: cannot serialise answer — %s", exc)
            return

        entry_id = str(uuid.uuid4())
        stored_at = datetime.now(timezone.utc).isoformat()

        # ChromaDB metadata values must be str | int | float | bool
        # Large JSON blobs need to be stored as a string field.
        metadata: dict = {
            "answer_json": answer_json,
            "stored_at": stored_at,
            "query_preview": query_text[:200],
            "paper_ids": ",".join(paper_ids) if paper_ids else "",
        }

        try:
            collection.add(
                ids=[entry_id],
                documents=[query_text],
                embeddings=[query_embedding],
                metadatas=[metadata],
            )
            logger.info(
                "AnswerCache.store: stored answer for query '%s…'",
                query_text[:60],
            )
        except Exception as exc:
            logger.error("AnswerCache.store: failed to store entry — %s", exc)

        # Opportunistic pruning: remove oldest entries if over the size cap
        try:
            count = collection.count()
            if count > _MAX_CACHE_SIZE:
                self._prune(collection, count - _MAX_CACHE_SIZE)
        except Exception:
            pass

    def _prune(self, collection, n_to_remove: int) -> None:
        """Remove the n_to_remove oldest entries from the cache collection."""
        try:
            all_entries = collection.get(include=["metadatas"])
            ids = all_entries.get("ids") or []
            metadatas = all_entries.get("metadatas") or []

            paired = list(zip(ids, metadatas))
            # Sort by stored_at ascending (oldest first)
            paired.sort(key=lambda x: x[1].get("stored_at", ""))

            ids_to_remove = [entry_id for entry_id, _ in paired[:n_to_remove]]
            if ids_to_remove:
                collection.delete(ids=ids_to_remove)
                logger.info("AnswerCache: pruned %d old entries", len(ids_to_remove))
        except Exception as exc:
            logger.error("AnswerCache._prune: error — %s", exc)

    async def stats(self) -> dict:
        """Return basic cache statistics."""
        collection = self._collection()
        try:
            count = collection.count()
        except Exception:
            count = 0
        return {
            "total_cached_answers": count,
            "similarity_threshold": self._get_threshold(),
        }


# Module-level singleton — agents import this directly
answer_cache = AnswerCache()
